### ISSUE TITLE
Add support for traffic priority?

### ISSUE THREAD

**Issue by ghost** [cryzed/TrafficToll#6]
subj

**Comment by cryzed** [comment]
What does "subj" mean? When I initially made this, I didn't consider traffic priority to be very useful if I'm already limiting the maximum bandwidth of applications. Can you elaborate on how you think this would be useful despite that?

**Comment by ghost** [comment]
Subj is a placeholder commonly used for situations when the title of a topic is self-explanatory. If it wasn't - it's my fault.

> When I initially made this, I didn't consider traffic priority to be very useful if I'm already limiting the maximum bandwidth of applications.

Tuning traffic priority has more to do with latency rather than with bandwidth.

> Can you elaborate on how you think this would be useful despite that?

The classic example is of a download app that can pass around data in big pieces with eventually big delays between them (because delays between these chunks are irrelevant). Versus for example a real time video stream, where you don't want to get lags while watching it online. Or a RT game, when you want a fluid experience and low pings (that's latency rather than bandwidth again).

I have noticed that TrafficToll uses tc behind the curtain and tc supports traffic prioritization. It's not an easy topic (subjectively I think it's much harder than grokking the basics of network filtering / firewalls for example).

Searching the manpage of tc for 'prio' shall get you started. And this https://lartc.org/howto/

**Comment by jerryr** [comment]
I would like to see this feature too. My primary case would be to prioritize interactive traffic (SSH, NFS for eg) while letting bulk traffic (torrents, for eg) take up the rest of the available bandwidth. I don't think this is possible with simply limiting the bandwidth: for instance, if there is no active interactive traffic, I want bulk traffic to use all of the bandwidth.

**Comment by cryzed** [comment]
@somospocos 
> Tuning traffic priority has more to do with latency rather than with bandwidth.

This cleared up everything already, thanks, I somehow didn't consider this.

> I have noticed that TrafficToll uses tc behind the curtain and tc supports traffic prioritization.

Well, yes, as I understood it certain QDiscs you can use _with_ tc support traffic prioritization, for example PRIO. But if I used this, then I would lose all traffic shaping capabilities (i.e. bandwidth limiting). Luckily the QDisc I researched and ended up using for TrafficToll back when I initially wrote it was HTB, which supports assigning priorities for leaf classes -- so in theory I should be able to get the best of both worlds.

@jerryr 
> I don't think this is possible with simply limiting the bandwidth: for instance, if there is no active interactive traffic, I want bulk traffic to use all of the bandwidth.

Yeah that makes sense. As mentioned above the HTB QDisc I used for TrafficToll should already support traffic prioritization, I just have to actually use it and read it from the config file. If that turns out to work then I'll add it, no problem. If it isn't as easy as I think, and I would have to switch to a different QDisc, then I'm not so sure -- I'd most likely lose the traffic shaping capabilities or have to do something much more complicated.

**Comment by cryzed** [comment]
Ok, you two can try installing this release [here](https://github.com/cryzed/TrafficToll/releases/tag/v1.1.0). I did two tests, and the traffic prioritization worked for me:

For one I limited the global download rate to 500kbps and started a game called "Path of Exile" and checked the ping. At this point it behaved extremely erratically and jumped from 300 to 1000+. After matching the process and setting "download-priority" and "upload-priority" to 0 (highest priority), the ping stayed stable at its usual value or slightly above it even while the download was running.

For the other I again limited the global download rate to 500kbps and tried to watch a YouTube video in Vivaldi. The video only loaded very slowly, if at all and while doing so, the displayed download rate in the program didn't change significantly. After assigning "download-priority" and "upload-priority" of 0 to Vivaldi I repeated the test, and the download rate in the download program dropped significantly and I could watch the YouTube video.

So it seems to create better latency and also prioritizes bandwidth used by processes. Please let me know how it works for you. Also if the log doesn't mention anything about "Shaping traffic for ..." then your process predicates are _not_ matching any processes and TrafficToll can't work. You have to create them properly.

You can see the new example configuration file [here](https://github.com/cryzed/TrafficToll/blob/develop/example.yaml) on the develop branch.

After a bit more testing, it seems like the global download/upload rates you define should not be higher than your real total download/upload, otherwise the priority settings will be useless -- the HTB QDisc will always assume that there's "excess traffic" it can borrow from the parent. So in case you don't see much happening, set the global "download" and "upload" rates to something resembling your real rates -- don't omit them, otherwise some huge max rate value will be used as default. As far as I see, when I add the root class to the HTB QDisc I _have_ to define some rate, and that will automatically be the limit all children can borrow from it, or the class itself can use. So to sum up: for traffic priority to work correctly you have to define an upper global download/upload rate limit which are your _real rates_, which will automatically limit your traffic to that maximum speed but allow the traffic prioritization to work. If you have any suggestions on how to improve this using the HTB QDisc let me know. Similar software like FireQOS also seems to need these fixed maximum download/upload rates.

**Comment by ghost** [comment]
I was able to reproduce the tests you did and it worked for me too.

The only additional thing (not directly related to this issue) I would find helpful as an end user would be source code release tarballs to contain a config sample file with generic examples. It seems like in its current state **tt -h** is not very helpful about the config structure and the only way to get a config file is to manually write one from scratch by using the README as reference or diving even deeper into the source code.

**Comment by cryzed** [comment]
Yes, I will add those, thanks for your feedback.

**Comment by cryzed** [comment]
Alright, I merged the changes into master, updated the README and the source build (tar.gz) now contains the "example.yaml". Theoretically it should also appear wherever the module itself is installed. Let me know if everything is to your liking and I'll close this.
