### ISSUE TITLE
TrafficToll is hard to install and run on Ubuntu 18.04

### ISSUE THREAD

**Issue by Hoimar** [cryzed/TrafficToll#7]
1. Had to download v1.3.1 because the `setup.py` file is missing in the latest version, so pip couldn't install the package.
1. It was important to use `pip3` for the installation.

Can 1. be fixed, and 2. perhaps be noted somewhere?
Otherwise, thanks for the great tool, @cryzed .

**Comment by cryzed** [comment]
Regarding

1) the `setup.py` isn't missing, it's automatically generated when I create a build of TrafficToll using `poetry build` -- it's just not part of the repository. You can find files which include the `setup.py` on the [releases](https://github.com/cryzed/TrafficToll/releases) page: the `.tar.gz` and `.whl` files. Additionally the instructions in the readme [tell you](https://github.com/cryzed/TrafficToll#installation) how you are supposed to install it, it won't work if you just point pip at the [Download ZIP](https://github.com/cryzed/TrafficToll/archive/master.zip).

2) When talking about `pip` in 2020 it's assumed to be Python 3, because [Python 2 is retired](https://pythonclock.org/) -- no new projects should be developed in Python 2. Seeing as TrafficToll is [marked as a Python 3 project](https://pypi.org/project/traffictoll/), I don't feel it's necessary to tell users to install with `pip3` specifically (if they even have that symlink on their system). I'll consider adding it to the README.

Glad you are enjoying TrafficToll.

**Comment by Hoimar** [comment]
Thanks for the clarifications. Being not very familiar with Python, I took me a bit to figure that out, among other things that didn't work well at first.
On my system, `pip` points to the Python 2 version, somehow even in 2020 :)
I tried using `$ pip install traffictoll` command, but it complained about not finding the package. Now it works though… perhaps I actually just tried it with `pip` instead of `pip3`.

**Comment by cryzed** [comment]
Yeah that seems to be a common point of confusion unfortunately, I tend to forget that not everyone is as familiar with the Python ecosystem -- sorry. As I said, I'll most likely add it to the README in the future. Thank you for your suggestion.

**Comment by cryzed** [comment]
@Hoimar I added a note to the [installation instructions](https://github.com/cryzed/TrafficToll#installation).
