### ISSUE TITLE
Unable to make it work

### ISSUE THREAD

**Issue by superbonaci** [cryzed/TrafficToll#8]
Installed as user `pip3 install traffictoll` then as root:

```
tt device config
ERROR: input grammar file 'device' does not exist; continuing...
ERROR: input grammar file 'config' does not exist; continuing...
```

**Comment by faishalirwn** [comment]
You have to replace "device" with your network interface, the one you connect to the internet with.
You can see your network interfaces with this command `ip link show`. 
The interface name is right after the number. Name that starts with "en" is for ethernet and "wl" is for wlan.

Replace "config" with .yaml config file. See the config example in the readme for reference. You can create it with text editor and save it with .yaml format.

**Comment by cryzed** [comment]
The error also seems to indicate that `tt` points to a different binary on his system, not TrafficToll. TrafficToll doesn't raise these kind of error messages. You might have conflicting names in your PATH.

**Comment by superbonaci** [comment]
Here is the command:

```
# which tt
/usr/bin/tt
# tt --help
Treetop Parsing Expression Grammar (PEG) Comand Line Compiler
Usage: tt [options] grammar_file[.treetop|.tt] ...

Examples:
  tt foo.tt               # 1 grammar -> 1 parser source
  tt foo bar.treetop      # 2 grammars -> 2 separate parsers
  tt -o alt_name.rb foo   # alternately named output file


NOTE: while treetop grammar files *must* have one of the following
filename extensions, the extension name is not required when calling
the compiler with grammar file names.

  Valid extensions: .treetop, .tt


Options:
    -o, --output FILENAME            Write parser source to FILENAME
    -f, --force                      Overwrite existing output file(s)
    -v, --version                    Show Treetop version
    -h, --help                       Show this help message
```

**Comment by superbonaci** [comment]
Ok I've located it as `/home/username/.local/bin/tt` but don't know what `config` to use. Using `day.yaml` says:

`FileNotFoundError: [Errno 2] No such file or directory: 'day.yaml'`

**Comment by superbonaci** [comment]
And please add such info to the README.md

**Comment by cryzed** [comment]
The error means exactly what it says. For general usage instructions, read the [usage](https://github.com/cryzed/TrafficToll#usage) section in the README.

> And please add such info to the README.md

No, this is basic Linux knowledge and falls outside the scope of TrafficToll.

**Comment by a1e7de48f89e** [comment]
@superbonaci The information you are looking for is clearly outlined [here](https://github.com/cryzed/TrafficToll#usage). I'm not sure what more you could be asking for.

You will have to create the `day.yaml` yourself (you can name the file however you want) and add the desired configuration there.

**Comment by superbonaci** [comment]
Ok thank you!

**Comment by Arcadio-Buendia** [comment]
My problem is slightly different but very similar. I am unable to make it work as well.
I installed it as
`sudo pip install traffictoll`
My config file is `speed.yaml` which has
```
download: 800kbps
upload: 800kbps
```
I launch the program as `sudo tt wlp1s0 ~/speed.yaml --delay 0.5`
to which I am shown 
```
2022-01-15 10:50:11.794 | INFO     | traffictoll.cli:main:146 - Setting up global class with max download rate: 800kbps (minimum: 100kbps) and priority: 0
2022-01-15 10:50:11.794 | INFO     | traffictoll.cli:main:168 - Setting up global class with max upload rate: 800kbps (minimum: 10kbps) and priority: 0

```
But when I do a speed test, I get 4.5mbps. 
I can't see where I am going wrong. 

I am on debian bullseye, and have tried with both i3 on X and sway on wayland.

**Comment by cryzed** [comment]
@Arcadio-Buendia First off, never install Python packages as the root-user, that's usually a bad idea because it creates untracked files in your Linux installation which are impossible to remove using your regular package manager. It's likely you will run into file conflicts with your package manager in the future, if you don't remove these untracked files again and install TrafficToll properly (either in a virtual environment, or using `$ pip install traffictoll --user`).

My guess is that you are either applying the rate-limiting to the wrong interface or you are falling for what I like to consider a marketing scam. 

If it's the first, make sure that you are applying the rate limiting to the correct interface, by checking which ones are available using `$ ip addr` and confirming that you are actually creating the traffic using that interface.

Alternatively you might be specifying a limit of 800kbps, or 800 kilobytes per second. The speed test you are using to measure, tells you that you have 4.5mbps or 4.5 megabits per second -- _not_ 4.5 megabytes per second. If you actually calculate what 4.5 megabits per second are in kilobytes per second:

`4.5 megabits per second = 4500 kilobits per second / 8 = 562.5 kilobytes per second`

So you are technically below the limit you specified. Try specifying 100 kilobyte per second instead, and see if your internet becomes slower and your speed test starts telling you something else.

**Comment by Arcadio-Buendia** [comment]
Thank you for the application and the explanation.
Yes, now I can see that I fell for the marketing scam.
Also, I will take that advice on Python packages.
